# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


'''Passos para fazer esse arquivo:
1 - Baixar o programa QT Designer em: https://build-system.fman.io/qt-designer-download
2 - Após a tela estar feita clique em FILE>SAVE AS... e salve como 'cadastro.ui'
3 - Abra o caminho de onde você salvou o arquivo pelo Windows Explorer e no local do caminho digite cmd para abrir o terminal pela pasta.
4 - Insira o seguinte comando: python -m PyQt6.uic.pyuic -o output.py -x input.ui
OBS: output é o nome do arquivo que você quer criar e input é o nome do arquivo que você deseja converter. Logo para funcionar input deverá ser 'cadastro'.
O código usado foi 'python -m PyQt6.uic.pyuic -o output.py -x cadastro.ui'
'''


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 601)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.produto = QtWidgets.QFrame(parent=self.centralwidget)
        self.produto.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.produto.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.produto.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.produto.setObjectName("produto")
        self.label_2 = QtWidgets.QLabel(parent=self.produto)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 151, 41))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.produto)
        self.cliente = QtWidgets.QFrame(parent=self.centralwidget)
        self.cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cliente.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cliente.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cliente.setObjectName("cliente")
        self.label = QtWidgets.QLabel(parent=self.cliente)
        self.label.setGeometry(QtCore.QRect(290, 10, 161, 41))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.cadastro = QtWidgets.QFrame(parent=self.cliente)
        self.cadastro.setGeometry(QtCore.QRect(9, 59, 761, 221))
        self.cadastro.setStyleSheet("background-color: rgb(158, 158, 158);")
        self.cadastro.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cadastro.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cadastro.setObjectName("cadastro")
        self.gridLayout = QtWidgets.QGridLayout(self.cadastro)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.cadastro)
        self.lineEdit_nome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_nome.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.gridLayout.addWidget(self.lineEdit_nome, 0, 0, 1, 3)
        self.lineEdit_email = QtWidgets.QLineEdit(parent=self.cadastro)
        self.lineEdit_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_email.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout.addWidget(self.lineEdit_email, 1, 0, 1, 3)
        self.lineEdit_telefone = QtWidgets.QLineEdit(parent=self.cadastro)
        self.lineEdit_telefone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_telefone.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_telefone.setObjectName("lineEdit_telefone")
        self.gridLayout.addWidget(self.lineEdit_telefone, 2, 0, 1, 1)
        self.lineEdit_data = QtWidgets.QLineEdit(parent=self.cadastro)
        self.lineEdit_data.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_data.setText("")
        self.lineEdit_data.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.gridLayout.addWidget(self.lineEdit_data, 2, 1, 1, 1)
        self.comboBox_categoria = QtWidgets.QComboBox(parent=self.cadastro)
        self.comboBox_categoria.setObjectName("comboBox_categoria")
        self.comboBox_categoria.addItem("")
        self.comboBox_categoria.addItem("")
        self.comboBox_categoria.addItem("")
        self.comboBox_categoria.addItem("")
        self.gridLayout.addWidget(self.comboBox_categoria, 2, 2, 1, 1)
        self.btn_cadastrar = QtWidgets.QPushButton(parent=self.cadastro)
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.gridLayout.addWidget(self.btn_cadastrar, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.cliente)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Produtos</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Clientes</span></p></body></html>"))
        self.lineEdit_nome.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.lineEdit_email.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.lineEdit_telefone.setPlaceholderText(_translate("MainWindow", "Telefone"))
        self.lineEdit_data.setPlaceholderText(_translate("MainWindow", "Data de Nascimento"))
        self.comboBox_categoria.setItemText(0, _translate("MainWindow", "Categorias"))
        self.comboBox_categoria.setItemText(1, _translate("MainWindow", "Ouro"))
        self.comboBox_categoria.setItemText(2, _translate("MainWindow", "Prata"))
        self.comboBox_categoria.setItemText(3, _translate("MainWindow", "Bronze"))
        self.btn_cadastrar.setText(_translate("MainWindow", "ENVIAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
