SELECT * FROM PRODUTO
SELECT * FROM CATEGORIA

SELECT CATEGORIA.NOME,
	CATEGORIA.ID_CATEGORIA, 
	COUNT(CATEGORIA.ID_CATEGORIA) AS PRODUTOSPORCATEGORIA
FROM PRODUTO
	JOIN CATEGORIA
		ON CATEGORIA.ID_CATEGORIA = PRODUTO.ID_CATEGORIA
GROUP BY CATEGORIA.ID_CATEGORIA, CATEGORIA.NOME
ORDER BY CATEGORIA.ID_CATEGORIA



SELECT *
FROM PRODUTO
	JOIN CATEGORIA
		ON CATEGORIA.ID_CATEGORIA = PRODUTO.ID_CATEGORIA
ORDER BY CATEGORIA.ID_CATEGORIA


SELECT * FROM PRODUTO
SELECT * FROM PEDIDO
SELECT * FROM PEDIDO_PRODUTOS
ORDER BY ID_PEDIDO

SELECT ID_PEDIDO,
	SUM(PEDIDO_PRODUTOS.QUANTIDADE) AS QUANTIDADEDEPRODUTOS,
	SUM(VALOR) AS VALORTOTAL
FROM PEDIDO_PRODUTOS
GROUP BY PEDIDO_PRODUTOS.ID_PEDIDO
ORDER BY ID_PEDIDO