CREATE TABLE CARRO(
ID_CARRO SERIAL PRIMARY KEY,
MARCA VARCHAR(30) NOT NULL,
MODELO VARCHAR(30) NOT NULL,
ANO INT
);

CREATE TABLE ALUGUEIS(
ID_ALUGUEL SERIAL PRIMARY KEY,
DIAS_ALUGUEL
ID_CARRO
ID_CLIENTE
);